Traceback (most recent call last):
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/main.py", line 38, in <module>
    app.run(main)
  File "/opt/anaconda3/lib/python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/main.py", line 33, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/train.py", line 29, in train_and_evaluate
    u_ref, t_star = get_dataset()
                    ^^^^^^^^^^^^^
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/utils.py", line 17, in get_dataset
    noise = random.normal(0,1,len(t))
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jax/_src/random.py", line 693, in normal
    key, _ = _check_prng_key("normal", key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jax/_src/random.py", line 79, in _check_prng_key
    wrapped_key = prng.random_wrap(key, impl=default_prng_impl())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jax/_src/prng.py", line 695, in random_wrap
    _check_prng_key_data(impl, base_arr)
  File "/opt/anaconda3/lib/python3.12/site-packages/jax/_src/prng.py", line 122, in _check_prng_key_data
    raise TypeError("JAX encountered invalid PRNG key data: expected key_data "
TypeError: JAX encountered invalid PRNG key data: expected key_data to have ndim, shape, and dtype attributes. Got 0
